stages:
  - test

serenity-api-tests:
  image: maven:3.9.0-eclipse-temurin-17
  stage: test
  before_script:
    - echo "Starting Serenity BDD API tests..."
  script:
    - mvn clean verify
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - target/site/serenity